#baseURL = 'https://blog.dacbd.dev/'
languageCode = 'en-us'
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
minifyOutput = true

[params]
title = 'The dacbd Blog'
subtitle = 'Technical Writings and Rants'
socialIcons = [{ name = "github", url = "https://github.com/dacbd" }, { name = "linkedin", url = "https://www.linkedin.com/in/dacbd/" }]
author = "Daniel Barnes"
defaultTheme = "dark"
env = "production"
mainSections = ["posts", "tags"]

# navigation things
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[markup.goldmark.renderer]
unsafe = true


[params.contact]
email = 'dabarnes2b@gmail.com'

[params.homeInfoParams]
Title = "Hello!"
Content = """
I'm Daniel Barnes, A software engineer who has done it all. I've always had a passion for programming and the internet.
I got started in tech at a local IT security company, where I learned Linux the hard way: given a backroom spare server, learned to close vi, then told to migrate some MySQL database to Postgres.

---
I've been professionally writing code since 2011 when I was introduced to Nodejs on `v0.4.0` and I've been writing code ever since.

---
50% Backend -> 30% DevOps -> 20% Frontend -> 0% Designer

Nodejs - Go - Rust - Python

"""

[params.cover]
hidden = true # hide everywhere but not in structured data
hiddenInList = true # hide on list pages and home
hiddenInSingle = false # hide on single page

[params.editPost]
URL = "https://github.com/dacbd/blog/content"
Text = "Suggest Changes" # edit text
appendFilePath = true # to append file path to Edit link

[menus]
[[menus.main]]
identifier = "home"
name = "home"
url = "/"
weight = 10
[[menus.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 20
[[menus.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30
[[menus.main]]
identifier = "dacbd.dev"
name = "dacbd.dev"
url = "https://blog.dacbd.dev"
weight = 100
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true
[markup.highlight]
noClasses = false
# anchorLineNos = true
# codeFences = true
# guessSyntax: = true
# lineNos = true
# style = monokai
